context('Customization', async () => {
    require('./editVirtualCurrency');
    require('./addTopBarInformation');
    require('./addBackground');
    require('./addBanner');
    require('./addSubSection');
    require('./addLogo');
    require('./editSocialLinks');
    require('./editSkin');
    require('./editIcons');
    require('./editColors');
    require('./editFooter');
    require('./addTopIcon');
    require('./addTypography');
    require('./addLoadingGif');
    require('./editTheme');
    require('./editEsportsScrenner')
    require('./editTopTab');
    require('./addLanguages')
});