name: Sync OAS to ReadMe
on:
  push:
    branches:
      - issue-735
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: MDhMrohs5sHAUcqe6K66rNDY9KrhH9Bn:5fa0651c6ba9867e6833a207
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './src/api/swagger/swagger.yaml'
          # api-version: 'v1.0.0'